apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: pawit-vetcare-migrate
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      taskCount: 1
      template:
        spec:
          maxRetries: 0
          timeoutSeconds: 600
          containers:
            - image: asia-south1-docker.pkg.dev/PROJECT_ID/pawit/pawit-vetcare-liquibase:COMMIT_SHA
              args:
                - update
              env:
                - name: LIQUIBASE_COMMAND_URL
                  valueFrom:
                    secretKeyRef:
                      name: pawit-liquibase-jdbc-url
                      key: latest
                - name: LIQUIBASE_COMMAND_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: pawit-database-username
                      key: latest
                - name: LIQUIBASE_COMMAND_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pawit-database-password
                      key: latest
